# =========================================
# PROFILE ATIVO
# =========================================

spring.profiles.active=dev

# =========================================
# JPA GLOBAL
# =========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect