# =====================================================
# DATABASE
# =====================================================

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA
# =====================================================

spring.jpa.show-sql=true

# =====================================================
# SUPABASE JWT
# =====================================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_ISSUER}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWK}

# =====================================================
# OLLAMA
# =====================================================

ollama.url=${OLLAMA_URL}

ollama.model=${OLLAMA_MODEL}